workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Run tests
        script: flutter test

      - name: Build Android App Bundle (.aab)
        script: flutter build appbundle --release

      # Or build an APK instead:
      # - name: Build APK
      #   script: flutter build apk --release

    artifacts:
      - build/app/outputs/**/*.aab
      # or for APK:
      # - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - your_email@example.com


